version: '3.1'

networks:
  app-tier:
    driver: bridge

services:
  nuxt:
    container_name: nuxt
    hostname: nuxt
    build:
      context: ./docker
    restart: unless-stopped
    user: root:root
    environment:
      - 'TZ=${TIMEZONE}'
      - 'PROJECT_DIR=${NUXTJS_DIR}'
      - 'NODE_ENV=${NODE_ENV}'
      - 'NODE_PORT=${NODE_PORT}'
      - 'SERVER_PATH_STAGING=${SERVER_PATH_FILE}'
      - 'SERVER_PATH_PRODUCTION=${SERVER_PATH_FILE}'
      - 'STAGING_APP=${STAGING_APP}'
      - 'PRODUCTION_APP=${PRODUCTION_APP}'
      - 'BUILD_FLAG=staging'
    networks:
      - app-tier
    expose:
      - '3000'
    volumes:
      - ./public-html:/app:rw

  httpd:
    container_name: nginx
    hostname: nginx
    image: bitnami/nginx:${NGINX_VERSION}-${OS_VERSION}
    user: root:root
    restart: unless-stopped
    environment:
      - 'TZ=${TIMEZONE}'
    depends_on:
      - nuxt
    networks:
      - app-tier
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./config/nginx/vhost:/opt/bitnami/nginx/conf/vhosts:rw
      - ./logs/nginx/${NGINX_VERSION}:/opt/bitnami/nginx/logs:rw
      - ./public-html:/app:rw
